Increase stack space overflow for pandoc.
I received a strange error when rendering basics.Rmd. Note that this did
not happen when pressing the "Knit HTML" button in RStudio, so they must
deal with this issue by default.

Stack space overflow: current size 16777216 bytes.
Use `+RTS -Ksize -RTS' to increase it.
Error: pandoc document conversion failed with error 2

I found this solution.

---
title: "Habits"
output:
 html_document:
 pandoc_args: [
 "+RTS", "-K64m",
 "-RTS"
 ]
---

http://stackoverflow.com/a/28015894

I don't always get this error, even for the same file. It must
depend on the spudling. I still added it just in case this problem
arises again.